"""
AI Core — Clean Interface for Person 3
========================================
Person 3 calls ONLY this function. Never imports agents/rag directly.

Usage by Person 3:
    from ai_core.main import process_query
    result = await process_query(request)
"""

from shared.schemas import AIProcessRequest, AIProcessResponse


async def process_query(request: AIProcessRequest) -> AIProcessResponse:
    """
    Main entry point for AI processing.
    
    Person 2 implements the full pipeline behind this function:
    1. Query Rewriting Agent
    2. Retriever Agent (FAISS search)
    3. Reasoning Agent
    4. Validator Agent  
    5. Explainer Agent
    
    Person 3 calls this function from the /query API endpoint.
    
    Args:
        request: AIProcessRequest with query, session info, history
        
    Returns:
        AIProcessResponse with answer, sources, confidence, explanation
    """
    # ─── MOCK RESPONSE (REPLACE WITH REAL PIPELINE) ───
    # Person 2: Replace this entire function body with your real pipeline.
    # Person 3: You can integrate immediately using this mock.
    
    return AIProcessResponse(
        answer=f"[MOCK] This is a placeholder response for: '{request.query}'. "
               f"Person 2 will implement the real RAG + agent pipeline here.",
        sources=["mock_safety_manual.pdf (page 1)", "mock_fire_protocol.pdf (page 3)"],
        confidence=0.85,
        explanation="[MOCK] This response was generated by the mock AI core. "
                    "The real system will use query rewriting, FAISS retrieval, "
                    "reasoning, validation, and explanation agents.",
        rewritten_query=request.query,
        agent_trace={
            "query_rewriter": "mock",
            "retriever": "mock",
            "reasoning": "mock",
            "validator": "mock",
            "explainer": "mock",
        },
    )
